---
- name: install and configure tomcat
  hosts: all
#  hosts: "{{myHosts}}"
  remote_user: root
  become: yes

  vars:
    tomcat_path: "/opt/tomcat10"


  tasks:
    - name: Remove apt lock file

      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/var/lib/dpkg/lock"
        - "/var/lib/dpkg/lock-frontend"
        - "/var/lib/apt/lists/lock"
        - "/var/cache/apt/archives/lock"



    - name: Update the System Packages
      apt:
        upgrade: yes
        update_cache: yes
        force_apt_get: yes

    - name: Create a Tomcat Group
      user:
        name: tomcat

    - name: Create a Tomcat Group
      group:
        name: tomcat

    - name: Install JAVA
      apt:
        name: openjdk-11-jdk
        state: present


    - name: Create a Tomcat Directory
      file:
        path: "{{ tomcat_path }}"
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes

    - name: download & unarchive tomcat10
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.83/bin/apache-tomcat-8.5.83.tar.gz
        dest: "{{ tomcat_path }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Change ownership of tomcat directory
      file:
        path: "{{ tomcat_path }}"
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: Copy Tomcat service from local to remote
      copy:
        src: tomcat.service
        dest: /etc/systemd/system/
        mode: 0755

    - name: Start and Enable Tomcat 10 on sever
      systemd:
        name: tomcat
        enabled: yes
        state: started
        daemon_reload: true
